import MeetupList from '../components/meetups/MeetupList.js';

const DUMMY_MEETUPS = [
    {
        id: 'm1',
        title: 'Meetup Title 1',
        image: 'https://img2.oastatic.com/img2/86691158/max/variant.jpg',
        address: 'Some address 1',
        description: 'Meetup description 1',
    },
    {
        id: 'm2',
        title: 'Meetup Title 2',
        image: 'https://img2.oastatic.com/img2/86691158/max/variant.jpg',
        address: 'Some address 2',
        description: 'Meetup description 2',
    }
];

const HomePage = (props) => {
    return (
        <MeetupList meetups={props.meetups} />
    );
}


// Static generation: only works on components of the pages/ directory. This functions executes during the prerendering
// process on the production build, means that the generated html code are in the source code, is not generated by js. 
// Allows async. Two options: getServerSideProps and getStaticProps

/*
// This is when you need to update the data on each request of the website. Only use if you need access to the req & res 
// to validate some authentication for example, or if the data really change every second, otherwhise its better to use 
// getStaticProps and makes the website faster 
export async function getServerSideProps(context) {
    const req = context.req;
    const res = context.res;

    // Any code here is running on the server side, never on the client side

    // Fetch data

    return {
        props: {
            meetups: DUMMY_MEETUPS
        }
    }
}
*/


// This allows to recive all necessary data before the components render, to avoid waiting to the fetching data. This
// way, the html of the MeetupList => MeetupItem is now available in the html base provided by the server
export async function getStaticProps() {
    // Any code here is running on the server side, never on the client side

    // Fetching data

    return {
        props: {
            meetups: DUMMY_MEETUPS
        },
        revalidate: 10 // incremental static generation: this page will regenerated each 10 seconds, so the pregenerated 
        // page ensure that have the updated data after the deployment
    };
}

export default HomePage
